# Generated by Django 4.2.18 on 2025-01-23 10:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('team_supported', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_pic', cloudinary.models.CloudinaryField(default='goals-profile-pic', max_length=255, verbose_name='image ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
