# Generated by Django 4.2.18 on 2025-01-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='goal_profile',
        ),
    ]
