# Generated by Django 4.2.18 on 2025-01-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_user_goal_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal_profile',
            old_name='name',
            new_name='user',
        ),
    ]
