# Generated by Django 4.2.18 on 2025-01-23 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0003_rename_name_goal_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal_profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='goal_profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
